import type { CategoryContent } from './row.js';

/**
 * market-panel — generated from DESIGN.md §7. IDS notation verbatim;
 * ui/glyphs.tsx draws it. `freqRank` (single characters only) is Jun Da's
 * Modern Chinese Character Frequency List (lingua.mtsu.edu/chinese-computing,
 * 193,504,018-character corpus, 9,933 distinct characters, dated 2004-03-30)
 * — a different corpus from the one DESIGN.md's own prose cites, so numbers
 * here do not match DESIGN.md's inline ranks character-for-character.
 * 保质期 is marked `transparency: 'opaque'` per DESIGN.md §3.3.3(8), which
 * names it as non-compositional ("no useful decomposition, learn this whole").
 *
 * 配料表/储存条件/生产厂家/许可证 (context-authoring phase, Aug 2026) carry real
 * GB 7718 back-panel fields as `context`, same pattern as 号 above. None of
 * the four has a verified `tier` placement in DESIGN.md's curriculum tables
 * or a verified Jun Da rank, so both are left unset rather than guessed.
 */
export const MARKET_PANEL: CategoryContent = {
  low: [
    [
      'On the back of the packet. What does it mean?',
      ['general measure word', 'garments, items, matters', 'half'],
      0,
      'gè · algemeen maatwoord (general measure word). Works for almost anything, so when in doubt, use this one.',
      { hanzi: '个', pinyin: 'gè', nl: 'algemeen maatwoord', en: 'general measure word' },
      undefined,
      { tier: 0, freqRank: 12 },
    ],
  ],
  mid: [
    [
      'On the back of the packet. What does it mean?',
      ['production date', '3, capital form', 'scan the QR code'],
      0,
      'shēngchǎn rìqī · productiedatum (production date).',
      { hanzi: '生产日期', pinyin: 'shēngchǎn rìqī', nl: 'productiedatum', en: 'production date' },
      undefined,
      { tier: 1 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['shelf life, as a duration', 'refrigerate, 0–4 °C', '3, capital form'],
      0,
      'bǎozhìqī · houdbaarheidsduur (shelf life). A number like 保质期12个月 tells you how long it lasts, not an actual date.',
      { hanzi: '保质期', pinyin: 'bǎozhìqī', nl: 'houdbaarheidsduur', en: 'shelf life, as a duration', transparency: 'opaque' },
      undefined,
      { tier: 1 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['net content', 'buy one get one free', 'freeze, −18 °C'],
      0,
      'jìnghánliàng · netto-inhoud (net content). Here 量 is read liàng, not liáng.',
      { hanzi: '净含量', pinyin: 'jìnghánliàng', nl: 'netto-inhoud', en: 'net content' },
      undefined,
      { tier: 1 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['refrigerate, 0–4 °C', 'members\' price', 'special price'],
      0,
      'lěngcáng · gekoeld bewaren (refrigerate, 0–4 °C). Shares its first character with 冷冻 (freeze) but means the opposite — worth telling apart.',
      { hanzi: '冷藏', pinyin: 'lěngcáng', nl: 'gekoeld bewaren', en: 'refrigerate, 0–4 °C' },
      undefined,
      { tier: 1 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['freeze, −18 °C', 'loose, sold by weight', 'yuan (written)'],
      0,
      'lěngdòng · diepvries (freeze, −18 °C). Easy to mix up with 冷藏 (refrigerate) — same first character, opposite instruction, and getting it wrong ruins the food.',
      { hanzi: '冷冻', pinyin: 'lěngdòng', nl: 'diepvries', en: 'freeze, −18 °C' },
      undefined,
      { tier: 1 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['imported', 'supermarket', 'special price'],
      0,
      'jìnkǒu · geïmporteerd (imported). On a metro sign the same two characters mean "entrance" instead.',
      { hanzi: '进口', pinyin: 'jìnkǒu', nl: 'geïmporteerd', en: 'imported' },
      undefined,
      { tier: 1 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['day of month (spoken); number', 'production date', 'special price'],
      0,
      'hào · dag (spreektaal); nummer (day of month, spoken; number). In writing you\'d use 日 for a date, but say hào out loud instead — the same pattern as writing 元 but saying 块 for money. Also the batch/lot number required on a food label, and the "number" on doors, platforms and bus stops.',
      {
        hanzi: '号',
        pinyin: 'hào',
        nl: 'dag (spreektaal); nummer',
        en: 'day of month (spoken); number',
        context: { before: '产品批', after: ' 20260815' },
      },
      undefined,
      { tier: 1, freqRank: 487 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['half', 'kilogram = 2 斤', 'hundred'],
      0,
      'bàn · half. Used for half past the hour, and also in 半份 (half portion) and 半斤 (250 g) on menus and at the market — one character, several everyday uses.',
      { hanzi: '半', pinyin: 'bàn', nl: 'half', en: 'half' },
      undefined,
      { tier: 1, freqRank: 513 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['portion, serving', 'half', 'buy one get one free'],
      0,
      'fèn · portie (portion, serving). Seen in 大份/中份/小份/半份 (large/medium/small/half portion) on menus. Looks similar to 分 (which can also be read fèn) — focus on what the word means rather than the tone.',
      { hanzi: '份', pinyin: 'fèn', nl: 'portie', en: 'portion, serving' },
      undefined,
      { tier: 1, freqRank: 784 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['cup, glass', 'checkout', '1, capital form'],
      0,
      'bēi · kopje, glas (cup, glass). Used for drinks. Written with the wood radical 木 on the left.',
      { hanzi: '杯', pinyin: 'bēi', nl: 'kopje, glas', en: 'cup, glass' },
      undefined,
      { tier: 1, freqRank: 1396 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['bowl', 'pairs', 'loose, sold by weight'],
      0,
      'wǎn · kom (bowl). Used for noodles, rice, congee — a common word on menus even though the character itself is rare elsewhere.',
      { hanzi: '碗', pinyin: 'wǎn', nl: 'kom', en: 'bowl' },
      undefined,
      { tier: 1, freqRank: 1939 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['bottle', 'yuan (spoken)', 'long thin things — fish, streets, trousers'],
      0,
      'píng · fles (bottle). Used for water, beer, sauce — also appears on shelf labels as a unit.',
      { hanzi: '瓶', pinyin: 'píng', nl: 'fles', en: 'bottle' },
      undefined,
      { tier: 1, freqRank: 1703 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['flat things — tickets, cards, tables', 'garments, items, matters', 'gram'],
      0,
      'zhāng · platte dingen — kaartjes, tafels (flat things — tickets, cards, tables). E.g. 一张票 (one ticket) — the word you need at a ticket window.',
      { hanzi: '张', pinyin: 'zhāng', nl: 'platte dingen — kaartjes, tafels', en: 'flat things — tickets, cards, tables' },
      undefined,
      { tier: 1, freqRank: 318 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['ingredient list', 'shelf life, as a duration', 'net content'],
      0,
      'pèiliào biǎo · ingrediëntenlijst (ingredient list). Ingredients are listed in descending order by weight, so whatever comes first is the main one.',
      {
        hanzi: '配料表',
        pinyin: 'pèiliào biǎo',
        nl: 'ingrediëntenlijst',
        en: 'ingredient list',
        context: { after: '：水、小麦粉、白砂糖、食用盐、酵母' },
      },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['storage conditions', 'refrigerate, 0–4 °C', 'net content'],
      0,
      'chǔcún tiáojiàn · bewaarcondities (storage conditions). Usually followed by something like 阴凉干燥处保存 (store in a cool, dry place) rather than an exact temperature.',
      {
        hanzi: '储存条件',
        pinyin: 'chǔcún tiáojiàn',
        nl: 'bewaarcondities',
        en: 'storage conditions',
        context: { after: '：阴凉干燥处保存，避免阳光直射' },
      },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['manufacturer', 'production date', 'imported'],
      0,
      'shēngchǎn chǎngjiā · fabrikant (manufacturer). Required alongside the address on every packaged-food label, distinct from 生产日期 (production date), which is a date, not a name.',
      {
        hanzi: '生产厂家',
        pinyin: 'shēngchǎn chǎngjiā',
        nl: 'fabrikant',
        en: 'manufacturer',
        context: { after: '：广东金穗食品有限公司' },
      },
    ],
  ],
  high: [
    [
      'On the back of the packet. What does it mean?',
      ['loose, sold by weight', 'shelf life, as a duration', 'freeze, −18 °C'],
      0,
      'sǎnzhuāng · los, per gewicht (loose, sold by weight). Signals that the price is per weight (yuan per jin), not a fixed price.',
      { hanzi: '散装', pinyin: 'sǎnzhuāng', nl: 'los, per gewicht', en: 'loose, sold by weight' },
      undefined,
      { tier: 2 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['weigh here', 'bottle', 'gram'],
      0,
      'chēngzhòng · hier afwegen (weigh here). Weigh loose produce and get a barcode sticker before you go to the till.',
      { hanzi: '称重', pinyin: 'chēngzhòng', nl: 'hier afwegen', en: 'weigh here' },
      undefined,
      { tier: 2 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['animals, one of a pair, some containers', 'net content', 'members\' price'],
      0,
      'zhī · dieren, één van een paar (measure word for animals, one of a pair, some containers). As "only", the same character is read zhǐ instead.',
      { hanzi: '只', pinyin: 'zhī', nl: 'dieren, één van een paar', en: 'animals, one of a pair, some containers' },
      undefined,
      { tier: 2, freqRank: 97 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['garments, items, matters', '1, capital form', 'general measure word'],
      0,
      'jiàn · kledingstukken, artikelen (garments, items, matters). E.g. 第二件半价 — "second item half price," a phrase you\'ll see in shops.',
      { hanzi: '件', pinyin: 'jiàn', nl: 'kledingstukken, artikelen', en: 'garments, items, matters' },
      undefined,
      { tier: 2, freqRank: 250 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['pairs', 'general measure word', '2, capital form'],
      0,
      'shuāng · paar (pairs). Shoes, chopsticks, socks. Written with 又 doubled — a visual hint at "a pair".',
      { hanzi: '双', pinyin: 'shuāng', nl: 'paar', en: 'pairs' },
      undefined,
      { tier: 2, freqRank: 581 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['long thin things — fish, streets, trousers', 'supermarket', 'special price'],
      0,
      'tiáo · lange dunne dingen — vis, straten, broeken (long thin things — fish, streets, trousers). E.g. 一条鱼 (one fish) on a market sign.',
      { hanzi: '条', pinyin: 'tiáo', nl: 'lange dunne dingen — vis, straten', en: 'long thin things — fish, streets, trousers' },
      undefined,
      { tier: 2, freqRank: 214 },
    ],
    [
      'On the back of the packet. What does it mean?',
      ['license', 'shelf life, as a duration', 'net content'],
      0,
      'xǔkězhèng · vergunning (license). On a food label this is the production licence, printed as 生产许可证编号 followed by an SC code (SC + 14 digits) — the mark that replaced the old QS logo in 2015.',
      {
        hanzi: '许可证',
        pinyin: 'xǔkězhèng',
        nl: 'vergunning',
        en: 'license',
        context: { before: '生产', after: '编号：SC11410115012345' },
      },
    ],
  ],
};
