import type { CategoryContent } from './row.js';

/** menu-animal — generated from DESIGN.md §7. IDS notation verbatim; ui/glyphs.tsx draws it. */
export const MENU_ANIMAL: CategoryContent = {
  low: [
    [
      'On the menu. What are you about to eat?',
      ['meat — by default pork', 'small portion', 'brain', 'kidney'],
      0,
      'ròu · vlees (meat) — on menus this means pork unless another meat is specified.',
      { hanzi: '肉', pinyin: 'ròu', nl: 'vlees — standaard varkensvlees' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['vegetarian', 'steam', 'house specialty', 'signature dish'],
      0,
      'sù · vegetarisch (vegetarian) — though "vegetarian" dishes are often still cooked with oyster sauce or meat stock.',
      { hanzi: '素', pinyin: 'sù', nl: 'vegetarisch' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['meat-containing', 'dumpling', 'steam', 'standard portion'],
      0,
      'hūn · met vlees (meat-containing) — often used as the "meat" heading paired against 素 ("vegetarian").',
      { hanzi: '荤', pinyin: 'hūn', nl: 'met vlees' },
    ],
  ],
  mid: [
    [
      'On the menu. What are you about to eat?',
      ['chicken', 'intestine', 'market price', 'flash-fry'],
      0,
      'jī · kip (chicken).',
      { hanzi: '鸡', pinyin: 'jī', nl: 'kip' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['beef', 'kidney', 'tendon', 'sweet'],
      0,
      'niú · rund (beef).',
      { hanzi: '牛', pinyin: 'niú', nl: 'rund' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['pig', 'covered braise', 'tongue', 'beef'],
      0,
      'zhū · varken (pig).',
      { hanzi: '猪', pinyin: 'zhū', nl: 'varken' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['lamb, mutton, goat', 'vegetarian', 'pan-fry', 'shrimp, prawn'],
      0,
      'yáng · lam, schaap, geit — one character covers lamb, mutton and goat.',
      { hanzi: '羊', pinyin: 'yáng', nl: 'lam, schaap, geit' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['fish', 'tongue', 'brain', 'dumpling'],
      0,
      'yú · vis (fish) — one of the most common proteins you\'ll see on a menu.',
      { hanzi: '鱼', pinyin: 'yú', nl: 'vis' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['shrimp, prawn', 'roast, grill', 'chicken', 'brain'],
      0,
      'xiā · garnaal (shrimp, prawn) — worth recognizing if you have a shellfish allergy.',
      { hanzi: '虾', pinyin: 'xiā', nl: 'garnaal' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['egg', 'sweet', 'soup', 'shrimp, prawn'],
      0,
      'dàn · ei (egg).',
      { hanzi: '蛋', pinyin: 'dàn', nl: 'ei' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['cooked rice; also "meal"', 'vegetarian', 'stir-fry', 'tossed, dressed'],
      0,
      'fàn · rijst, maaltijd (cooked rice; also "meal") — as in 炒饭 (fried rice), 米饭 (steamed rice).',
      { hanzi: '饭', pinyin: 'fàn', nl: 'rijst, maaltijd' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['wheat noodles; also "flour"', 'pan-fry', 'meat-containing', 'shrimp, prawn'],
      0,
      'miàn · tarwenoedels (wheat noodles; also "flour"). Shows up in compounds like 面馆 (noodle shop).',
      { hanzi: '面', pinyin: 'miàn', nl: 'tarwenoedels' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['rice noodles; also "powder"', 'swish in broth', 'staples: rice, noodles, buns', 'chicken'],
      0,
      'fěn · rijstnoedels (rice noodles) — the same character can also mean "powder", but on a menu it means noodles.',
      { hanzi: '粉', pinyin: 'fěn', nl: 'rijstnoedels' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['dumpling', 'rice noodles; also "powder"', 'boil', 'liver'],
      0,
      'jiǎo · dumpling.',
      { hanzi: '饺', pinyin: 'jiǎo', nl: 'dumpling' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['filled steamed bun', 'tendon', 'swish in broth', 'gizzard'],
      0,
      'bāo · gevuld gestoomd broodje (filled steamed bun) — unlike 馒头, which is the plain, unfilled version.',
      { hanzi: '包', pinyin: 'bāo', nl: 'gevuld gestoomd broodje' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['pot', 'large portion', 'small portion', 'meat — by default pork'],
      0,
      'guō · pan, pot (pot) — as in 火锅 (hotpot), 砂锅 (clay pot), 干锅 (dry pot).',
      { hanzi: '锅', pinyin: 'guō', nl: 'pan' },
    ],
  ],
  high: [
    [
      'On the menu. What are you about to eat?',
      ['intestine', 'pan-fry', 'large portion', 'master-stock braise'],
      0,
      'cháng · darm (intestine) — as in 肥肠, 大肠.',
      { hanzi: '肠', pinyin: 'cháng', nl: 'darm' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['tripe, stomach', 'liver', 'stir-fry', 'tendon'],
      0,
      'dǔ · pens, maag (tripe, stomach) — as in 毛肚 on hotpot menus. Read with a different tone, dù, it instead means "belly".',
      { hanzi: '肚', pinyin: 'dǔ', nl: 'pens, maag' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['liver', 'cold dishes', 'lung', 'sweet'],
      0,
      'gān · lever (liver) — as in 猪肝 (pork liver), 鹅肝 (foie gras).',
      { hanzi: '肝', pinyin: 'gān', nl: 'lever' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['kidney', 'boil', 'cold dishes', 'wheat noodles; also "flour"'],
      0,
      'yāo · nier (kidney) — as in 腰花. The same character also means "waist".',
      { hanzi: '腰', pinyin: 'yāo', nl: 'nier' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['lung', 'pot', 'sweet', 'wheat noodles; also "flour"'],
      0,
      'fèi · long (lung) — despite its name, 夫妻肺片 no longer actually contains lung.',
      { hanzi: '肺', pinyin: 'fèi', nl: 'long' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['kidney', 'swish in broth', 'gizzard', 'large portion'],
      0,
      'shèn · nier (kidney).',
      { hanzi: '肾', pinyin: 'shèn', nl: 'nier' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['brain', 'steam', 'large portion', 'master-stock braise'],
      0,
      'nǎo · hersenen (brain) — as in 脑花.',
      { hanzi: '脑', pinyin: 'nǎo', nl: 'hersenen' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['gizzard', 'soft drinks', 'large portion', 'signature dish'],
      0,
      'zhēn · spiermaag (gizzard).',
      { hanzi: '胗', pinyin: 'zhēn', nl: 'spiermaag' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['blood, as a set curd', 'swish in broth', 'liver', 'standard portion'],
      0,
      'xuè · bloed, als gestolde koek (blood, served as a set curd) — as in 鸭血 (duck blood), 毛血旺.',
      { hanzi: '血', pinyin: 'xuè', nl: 'bloed, als gestolde koek' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['tongue', 'signature dish', 'egg', 'blood, as a set curd'],
      0,
      'shé · tong (tongue) — as in 牛舌 (beef tongue).',
      { hanzi: '舌', pinyin: 'shé', nl: 'tong' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['tendon', 'kidney', 'market price', 'standard portion'],
      0,
      'jīn · pees (tendon).',
      { hanzi: '筋', pinyin: 'jīn', nl: 'pees' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['skin, crackling', 'pig', 'kidney', 'signature dish'],
      0,
      'pí · huid, zwoerd (skin, crackling) — as in 猪皮 (pork skin), 皮蛋 (preserved egg).',
      { hanzi: '皮', pinyin: 'pí', nl: 'huid, zwoerd' },
    ],
  ],
};
