import type { CategoryContent } from './row.js';

/** menu-animal — generated from DESIGN.md §7. IDS notation verbatim; ui/glyphs.tsx draws it. */
export const MENU_ANIMAL: CategoryContent = {
  low: [
    [
      'On the menu. What are you about to eat?',
      ['meat — by default pork', 'small portion', 'brain', 'kidney'],
      0,
      'ròu · vlees — standaard varkensvlees. The single most consequential unmarked default on the page',
      { hanzi: '肉', pinyin: 'ròu', nl: 'vlees — standaard varkensvlees' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['vegetarian', 'steam', 'house specialty', 'signature dish'],
      0,
      'sù · vegetarisch. But 素 dishes routinely carry 蚝油 or 高汤',
      { hanzi: '素', pinyin: 'sù', nl: 'vegetarisch' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['meat-containing', 'dumpling', 'steam', 'standard portion'],
      0,
      'hūn · met vlees. Rank 3,302, absent from HSK 3.0; pairs with 素 as a menu-header opposition',
      { hanzi: '荤', pinyin: 'hūn', nl: 'met vlees' },
    ],
  ],
  mid: [
    [
      'On the menu. What are you about to eat?',
      ['chicken', 'intestine', 'market price', 'flash-fry'],
      0,
      'jī · kip. Rank 1,249',
      { hanzi: '鸡', pinyin: 'jī', nl: 'kip' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['beef', 'kidney', 'tendon', 'sweet'],
      0,
      'niú · rund. Rank 881',
      { hanzi: '牛', pinyin: 'niú', nl: 'rund' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['pig', 'covered braise', 'tongue', 'beef'],
      0,
      'zhū · varken. Rank 1,633 — outside the frequency bank',
      { hanzi: '猪', pinyin: 'zhū', nl: 'varken' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['lamb, mutton, goat', 'vegetarian', 'pan-fry', 'shrimp, prawn'],
      0,
      'yáng · lam, schaap, geit. Rank 1,340; the Dutch gloss is genuinely three animals',
      { hanzi: '羊', pinyin: 'yáng', nl: 'lam, schaap, geit' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['fish', 'tongue', 'brain', 'dumpling'],
      0,
      'yú · vis. Rank 452, the highest-frequency protein',
      { hanzi: '鱼', pinyin: 'yú', nl: 'vis' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['shrimp, prawn', 'roast, grill', 'chicken', 'brain'],
      0,
      'xiā · garnaal. Rank 2,460; allergen-critical',
      { hanzi: '虾', pinyin: 'xiā', nl: 'garnaal' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['egg', 'sweet', 'soup', 'shrimp, prawn'],
      0,
      'dàn · ei. Rank 1,157',
      { hanzi: '蛋', pinyin: 'dàn', nl: 'ei' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['cooked rice; also "meal"', 'vegetarian', 'stir-fry', 'tossed, dressed'],
      0,
      'fàn · rijst, maaltijd. 炒饭, 米饭',
      { hanzi: '饭', pinyin: 'fàn', nl: 'rijst, maaltijd' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['wheat noodles; also "flour"', 'pan-fry', 'meat-containing', 'shrimp, prawn'],
      0,
      'miàn · tarwenoedels. Rank 76, but the food sense is what\'s needed. Traditional 麵 appears on calligraphic 麵館 fascias',
      { hanzi: '面', pinyin: 'miàn', nl: 'tarwenoedels' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['rice noodles; also "powder"', 'swish in broth', 'staples: rice, noodles, buns', 'chicken'],
      0,
      'fěn · rijstnoedels. One reading, two senses — both on menus',
      { hanzi: '粉', pinyin: 'fěn', nl: 'rijstnoedels' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['dumpling', 'rice noodles; also "powder"', 'boil', 'liver'],
      0,
      'jiǎo · dumpling. Rank 3,891 — a frequency bank never reaches it',
      { hanzi: '饺', pinyin: 'jiǎo', nl: 'dumpling' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['filled steamed bun', 'tendon', 'swish in broth', 'gizzard'],
      0,
      'bāo · gevuld gestoomd broodje. Contrasts with 馒头, which is unfilled',
      { hanzi: '包', pinyin: 'bāo', nl: 'gevuld gestoomd broodje' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['pot', 'large portion', 'small portion', 'meat — by default pork'],
      0,
      'guō · pan. Rank 1,520. 火锅 hotpot, 砂锅 clay pot, 干锅 dry pot',
      { hanzi: '锅', pinyin: 'guō', nl: 'pan' },
    ],
  ],
  high: [
    [
      'On the menu. What are you about to eat?',
      ['intestine', 'pan-fry', 'large portion', 'master-stock braise'],
      0,
      'cháng · darm. 肥肠, 大肠. Rank 1,512 — twelve places outside the bank',
      { hanzi: '肠', pinyin: 'cháng', nl: 'darm' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['tripe, stomach', 'liver', 'stir-fry', 'tendon'],
      0,
      'dǔ · pens, maag. 毛肚 on every hotpot sheet. Read dù it means "belly"',
      { hanzi: '肚', pinyin: 'dǔ', nl: 'pens, maag' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['liver', 'cold dishes', 'lung', 'sweet'],
      0,
      'gān · lever. 猪肝, 鹅肝. Rank 1,829',
      { hanzi: '肝', pinyin: 'gān', nl: 'lever' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['kidney', 'boil', 'cold dishes', 'wheat noodles; also "flour"'],
      0,
      'yāo · nier. 腰花. Rank 1,489 — the one organ character a 1,500 bank would have given you, eleven places inside. Also means "waist"',
      { hanzi: '腰', pinyin: 'yāo', nl: 'nier' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['lung', 'pot', 'sweet', 'wheat noodles; also "flour"'],
      0,
      'fèi · long. 夫妻肺片 contains no lung nowadays. Rank 2,140',
      { hanzi: '肺', pinyin: 'fèi', nl: 'long' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['kidney', 'swish in broth', 'gizzard', 'large portion'],
      0,
      'shèn · nier. Rank 2,131',
      { hanzi: '肾', pinyin: 'shèn', nl: 'nier' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['brain', 'steam', 'large portion', 'master-stock braise'],
      0,
      'nǎo · hersenen. 脑花. Rank 909 — high frequency, wrong sense',
      { hanzi: '脑', pinyin: 'nǎo', nl: 'hersenen' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['gizzard', 'soft drinks', 'large portion', 'signature dish'],
      0,
      'zhēn · spiermaag. Rank 7,674. The clearest single case for a functional syllabus',
      { hanzi: '胗', pinyin: 'zhēn', nl: 'spiermaag' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['blood, as a set curd', 'swish in broth', 'liver', 'standard portion'],
      0,
      'xuè · bloed, als gestolde koek. 鸭血, 毛血旺. Does not carry the flesh component',
      { hanzi: '血', pinyin: 'xuè', nl: 'bloed, als gestolde koek' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['tongue', 'signature dish', 'egg', 'blood, as a set curd'],
      0,
      'shé · tong. 牛舌. Rank 1,914. Does not carry the flesh component',
      { hanzi: '舌', pinyin: 'shé', nl: 'tong' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['tendon', 'kidney', 'market price', 'standard portion'],
      0,
      'jīn · pees. Kangxi radical is 竹 (bamboo); the flesh component hides one level down, inside 肋',
      { hanzi: '筋', pinyin: 'jīn', nl: 'pees' },
    ],
    [
      'On the menu. What are you about to eat?',
      ['skin, crackling', 'pig', 'kidney', 'signature dish'],
      0,
      'pí · huid, zwoerd. 猪皮, 皮蛋. Does not carry the flesh component',
      { hanzi: '皮', pinyin: 'pí', nl: 'huid, zwoerd' },
    ],
  ],
};
