import type { CategoryContent } from './row.js';

/** street-trade — generated from DESIGN.md §7, filed by GB 2894 category. */
export const STREET_TRADE: CategoryContent = {
  low: [
    [
      'On a shopfront. What is this place?',
      ['toilet (blunt)', 'tea', 'hotpot', 'laundry'],
      0,
      'cèsuǒ · wc. ⿸厂则; 厕 侧 测 all read cè, though 则 itself is zé — the series predicts across derivatives, not from the phonetic. 所 = ⿰户斤, rank 100.',
      { hanzi: '厕所', pinyin: 'cèsuǒ', nl: 'wc' },
    ],
    [
      'On a shopfront. What is this place?',
      ['washroom (polite)', 'coffee', 'petrol station', 'hotel (larger)'],
      0,
      'xǐshǒujiān · toilet. Band 1. 手 (138) and 间 (144) are top-150, but 洗 is rank 1,376 and needs its own exposure. The register gap from 厕所 is the taught content.',
      { hanzi: '洗手间', pinyin: 'xǐshǒujiān', nl: 'toilet' },
    ],
  ],
  mid: [
    [
      'On a shopfront. What is this place?',
      ['pharmacy', 'car park', 'laundry', 'snacks, cheap eats'],
      0,
      'yàodiàn · apotheek. Band 2. ⿱艹约, 9 strokes; traditional 藥 is 19 and never ships. Green cross livery arrives before the characters.',
      { hanzi: '药店', pinyin: 'yàodiàn', nl: 'apotheek' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hospital', 'snacks, cheap eats', 'barber, hairdresser', 'restaurant or hotel'],
      0,
      'yīyuàn · ziekenhuis. Band 1. ⿰阝完, 阝 on the left (mound, 阜). Contrast 邮. 急诊 is A&E.',
      { hanzi: '医院', pinyin: 'yīyuàn', nl: 'ziekenhuis' },
    ],
    [
      'On a shopfront. What is this place?',
      ['bank', 'noodle shop', 'post office', 'restaurant'],
      0,
      'yínháng · bank. Band 2, the 行 = háng exemplar. ⿰钅艮 — but 根 gēn, 很 hěn, 跟 gēn scatter on initials and 银 yín fits worst: a shape cue, not a rule.',
      { hanzi: '银行', pinyin: 'yínháng', nl: 'bank' },
    ],
    [
      'On a shopfront. What is this place?',
      ['post office', 'snacks, cheap eats', 'clinic', 'car park'],
      0,
      'yóujú · postkantoor. Band 4. ⿰由阝, 阝 on the right (settlement, 邑) — a different component from the 阝 in 院 despite identical rendering and codepoint, U+961D. Store per item. Green livery.',
      { hanzi: '邮局', pinyin: 'yóujú', nl: 'postkantoor' },
    ],
    [
      'On a shopfront. What is this place?',
      ['local police station', 'noodle shop', 'hotel (mid-range)', 'snacks, cheap eats'],
      0,
      'pàichūsuǒ · politiebureau. Absent from every band. Where a lost passport is reported; 出入境管理 handles visas.',
      { hanzi: '派出所', pinyin: 'pàichūsuǒ', nl: 'politiebureau' },
    ],
    [
      'On a shopfront. What is this place?',
      ['courier, parcel point', 'washroom (polite)', 'barber, hairdresser', 'hotpot'],
      0,
      'kuàidì · pakketpunt. Band 4. ⿺辶弟, 弟 dì giving 递 dì, tone and all — the one fully transparent phonetic here. Fascias read 顺丰, 菜鸟驿站.',
      { hanzi: '快递', pinyin: 'kuàidì', nl: 'pakketpunt' },
    ],
    [
      'On a shopfront. What is this place?',
      ['petrol station', 'local police station', 'restaurant or hotel', 'hospital'],
      0,
      'jiāyóuzhàn · tankstation. Band 4. Reuses 站 from 7.3 in a different sense — a contexts entry for the graduation gate.',
      { hanzi: '加油站', pinyin: 'jiāyóuzhàn', nl: 'tankstation' },
    ],
    [
      'On a shopfront. What is this place?',
      ['car park', 'petrol station', 'washroom (polite)', 'hospital'],
      0,
      'tíngchēchǎng · parkeerplaats. Band 2. Reuses 场 and 车. Signed P.',
      { hanzi: '停车场', pinyin: 'tíngchēchǎng', nl: 'parkeerplaats' },
    ],
  ],
  high: [
    [
      'On a shopfront. What is this place?',
      ['clinic', 'laundry', 'hotel (larger)', 'local police station'],
      0,
      'zhěnsuǒ · huisartsenpraktijk. Band 7–9, rank 1,906. 讠 on the left (speech); 讠 recurs in 证, 话, 语.',
      { hanzi: '诊所', pinyin: 'zhěnsuǒ', nl: 'huisartsenpraktijk' },
    ],
    [
      'On a shopfront. What is this place?',
      ['barber, hairdresser', 'washroom (polite)', 'hotel (mid-range)', 'restaurant'],
      0,
      'lǐfà · kapper. Band 3. 发 reads fà here, not fā, stored per item. Lint case: 理发 → 理髮, not 理發.',
      { hanzi: '理发', pinyin: 'lǐfà', nl: 'kapper' },
    ],
    [
      'On a shopfront. What is this place?',
      ['laundry', 'barber, hairdresser', 'local police station', 'petrol station'],
      0,
      'xǐyī · wasserij. Absent from HSK. Reuses 洗 from 洗手间, and at rank 1,376 that reuse does real work.',
      { hanzi: '洗衣', pinyin: 'xǐyī', nl: 'wasserij' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hotel (larger)', 'snacks, cheap eats', 'coffee', 'hotpot'],
      0,
      'jiǔdiàn · hotel. Band 2. ⿰氵酉, radical of record 酉 (fermented). Foil: 洒 sǎ = ⿰氵西.',
      { hanzi: '酒店', pinyin: 'jiǔdiàn', nl: 'hotel' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hotel (mid-range)', 'post office', 'hospital', 'clinic'],
      0,
      'bīnguǎn · hotel. Band 5. ⿱宀兵, rank 1,630. 招待所 is basic and often refuses foreigners.',
      { hanzi: '宾馆', pinyin: 'bīnguǎn', nl: 'hotel' },
    ],
    [
      'On a shopfront. What is this place?',
      ['restaurant or hotel', 'restaurant', 'clinic', 'snacks, cheap eats'],
      0,
      'fàndiàn · restaurant of hotel. The trap item. Band 1 word, band 1 characters, ambiguous compound.',
      { hanzi: '饭店', pinyin: 'fàndiàn', nl: 'restaurant of hotel' },
    ],
    [
      'On a shopfront. What is this place?',
      ['restaurant', 'restaurant or hotel', 'bank', 'tea'],
      0,
      'cāntīng · restaurant. Band 5. 餐 = ⿱⿰歺又食 (the 食 form, not 饣); 厅 = ⿸厂丁. Unambiguous where 饭店 is not.',
      { hanzi: '餐厅', pinyin: 'cāntīng', nl: 'restaurant' },
    ],
    [
      'On a shopfront. What is this place?',
      ['snacks, cheap eats', 'restaurant', 'noodle shop', 'hospital'],
      0,
      'xiǎochī · snackbar. Band 4. Not a head but a specialiser appearing alone on a fascia. The cheapest hot food in China.',
      { hanzi: '小吃', pinyin: 'xiǎochī', nl: 'snackbar' },
    ],
    [
      'On a shopfront. What is this place?',
      ['noodle shop', 'barber, hairdresser', 'hotel (mid-range)', 'restaurant or hotel'],
      0,
      'miànguǎn · noedelzaak. Absent from HSK. Lint case: 面馆 → 麵館, never 面館.',
      { hanzi: '面馆', pinyin: 'miànguǎn', nl: 'noedelzaak' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hotpot', 'restaurant or hotel', 'local police station', 'restaurant'],
      0,
      'huǒguō · hotpot. Band 7–9. ⿰钅呙 — 钅 a fourth time across the two sections.',
      { hanzi: '火锅', pinyin: 'huǒguō', nl: 'hotpot' },
    ],
    [
      'On a shopfront. What is this place?',
      ['coffee', 'hotel (mid-range)', 'laundry', 'snacks, cheap eats'],
      0,
      'kāfēi · koffie. Band 3, ranks 2,620 and 2,581. ⿰口加 and ⿰口非: the semantic read fails, the phonetic read works (非 fēi → 啡 fēi), and 口 on a rare character flags a transcription.',
      { hanzi: '咖啡', pinyin: 'kāfēi', nl: 'koffie' },
    ],
    [
      'On a shopfront. What is this place?',
      ['tea', 'petrol station', 'pharmacy', 'hotel (mid-range)'],
      0,
      'chá · thee. ⿱艹⿱人木, rank 851, band 1. 茶楼 teahouse, 奶茶 bubble tea.',
      { hanzi: '茶', pinyin: 'chá', nl: 'thee' },
    ],
  ],
};
