import type { CategoryContent } from './row.js';

/** street-trade — generated from DESIGN.md §7, filed by GB 2894 category. */
export const STREET_TRADE: CategoryContent = {
  low: [
    [
      'On a shopfront. What is this place?',
      ['toilet (blunt)', 'tea', 'hotpot', 'laundry'],
      0,
      'cèsuǒ · wc (blunt word for toilet). 厕 shares its reading with 侧 and 测, but the part it\'s built from, 则, is actually read zé — so that part alone won\'t tell you the sound.',
      { hanzi: '厕所', pinyin: 'cèsuǒ', nl: 'wc' },
    ],
    [
      'On a shopfront. What is this place?',
      ['washroom (polite)', 'coffee', 'petrol station', 'hotel (larger)'],
      0,
      'xǐshǒujiān · washroom (the polite word for toilet). 手 (hand) and 间 (room) are both very common, but 洗 (wash) is much rarer and worth learning on its own.',
      { hanzi: '洗手间', pinyin: 'xǐshǒujiān', nl: 'toilet' },
    ],
  ],
  mid: [
    [
      'On a shopfront. What is this place?',
      ['pharmacy', 'car park', 'laundry', 'snacks, cheap eats'],
      0,
      'yàodiàn · apotheek (pharmacy). Look for the green cross sign — it marks a pharmacy just like in many European countries.',
      { hanzi: '药店', pinyin: 'yàodiàn', nl: 'apotheek' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hospital', 'snacks, cheap eats', 'barber, hairdresser', 'restaurant or hotel'],
      0,
      'yīyuàn · ziekenhuis (hospital). Don\'t mix it up with 邮 (mail) — they look similar at a glance. 急诊 means "emergency room."',
      { hanzi: '医院', pinyin: 'yīyuàn', nl: 'ziekenhuis' },
    ],
    [
      'On a shopfront. What is this place?',
      ['bank', 'noodle shop', 'post office', 'restaurant'],
      0,
      'yínháng · bank. Note that 行 is read háng here, not the more common xíng — it\'s a heteronym worth remembering.',
      { hanzi: '银行', pinyin: 'yínháng', nl: 'bank' },
    ],
    [
      'On a shopfront. What is this place?',
      ['post office', 'snacks, cheap eats', 'clinic', 'car park'],
      0,
      'yóujú · postkantoor (post office). Usually marked with green signage.',
      { hanzi: '邮局', pinyin: 'yóujú', nl: 'postkantoor' },
    ],
    [
      'On a shopfront. What is this place?',
      ['local police station', 'noodle shop', 'hotel (mid-range)', 'snacks, cheap eats'],
      0,
      'pàichūsuǒ · politiebureau (local police station). This is where you\'d report a lost passport.',
      { hanzi: '派出所', pinyin: 'pàichūsuǒ', nl: 'politiebureau' },
    ],
    [
      'On a shopfront. What is this place?',
      ['courier, parcel point', 'washroom (polite)', 'barber, hairdresser', 'hotpot'],
      0,
      'kuàidì · pakketpunt (courier/parcel pickup point). 递 is pronounced dì, exactly like its 弟 component — a rare case where the shape gives you the full sound. Common signage reads 顺丰 or 菜鸟驿站.',
      { hanzi: '快递', pinyin: 'kuàidì', nl: 'pakketpunt' },
    ],
    [
      'On a shopfront. What is this place?',
      ['petrol station', 'local police station', 'restaurant or hotel', 'hospital'],
      0,
      'jiāyóuzhàn · tankstation (petrol station). 站 (station) also shows up in words for bus and train stations.',
      { hanzi: '加油站', pinyin: 'jiāyóuzhàn', nl: 'tankstation' },
    ],
    [
      'On a shopfront. What is this place?',
      ['car park', 'petrol station', 'washroom (polite)', 'hospital'],
      0,
      'tíngchēchǎng · parkeerplaats (car park). Often just marked with a big letter P.',
      { hanzi: '停车场', pinyin: 'tíngchēchǎng', nl: 'parkeerplaats' },
    ],
  ],
  high: [
    [
      'On a shopfront. What is this place?',
      ['clinic', 'laundry', 'hotel (larger)', 'local police station'],
      0,
      'zhěnsuǒ · huisartsenpraktijk (clinic). 诊 uses the 讠 (speech) radical, also seen in 证 and 话.',
      { hanzi: '诊所', pinyin: 'zhěnsuǒ', nl: 'huisartsenpraktijk' },
    ],
    [
      'On a shopfront. What is this place?',
      ['barber, hairdresser', 'washroom (polite)', 'hotel (mid-range)', 'restaurant'],
      0,
      'lǐfà · kapper (barber/hairdresser). Here 发 is read fà, not the more common fā — worth remembering for this word specifically.',
      { hanzi: '理发', pinyin: 'lǐfà', nl: 'kapper' },
    ],
    [
      'On a shopfront. What is this place?',
      ['laundry', 'barber, hairdresser', 'local police station', 'petrol station'],
      0,
      'xǐyī · wasserij (laundry). Same 洗 (wash) character as in 洗手间 — worth recognizing on sight.',
      { hanzi: '洗衣', pinyin: 'xǐyī', nl: 'wasserij' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hotel (larger)', 'snacks, cheap eats', 'coffee', 'hotpot'],
      0,
      'jiǔdiàn · hotel. 酒 (wine/alcohol) is built from 酉, a component tied to fermentation. Don\'t confuse it with the similar-looking 洒 (sǎ, "to sprinkle").',
      { hanzi: '酒店', pinyin: 'jiǔdiàn', nl: 'hotel' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hotel (mid-range)', 'post office', 'hospital', 'clinic'],
      0,
      'bīnguǎn · hotel (mid-range). 招待所 are cheaper guesthouses that often won\'t accept foreign guests.',
      { hanzi: '宾馆', pinyin: 'bīnguǎn', nl: 'hotel' },
    ],
    [
      'On a shopfront. What is this place?',
      ['restaurant or hotel', 'restaurant', 'clinic', 'snacks, cheap eats'],
      0,
      'fàndiàn · restaurant or hotel — the word itself is genuinely ambiguous, so you need context to tell which one it is.',
      { hanzi: '饭店', pinyin: 'fàndiàn', nl: 'restaurant of hotel' },
    ],
    [
      'On a shopfront. What is this place?',
      ['restaurant', 'restaurant or hotel', 'bank', 'tea'],
      0,
      'cāntīng · restaurant. Unlike 饭店, this word unambiguously means restaurant, not hotel.',
      { hanzi: '餐厅', pinyin: 'cāntīng', nl: 'restaurant' },
    ],
    [
      'On a shopfront. What is this place?',
      ['snacks, cheap eats', 'restaurant', 'noodle shop', 'hospital'],
      0,
      'xiǎochī · snackbar (cheap eats). Usually the cheapest hot food you\'ll find on the street.',
      { hanzi: '小吃', pinyin: 'xiǎochī', nl: 'snackbar' },
    ],
    [
      'On a shopfront. What is this place?',
      ['noodle shop', 'barber, hairdresser', 'hotel (mid-range)', 'restaurant or hotel'],
      0,
      'miànguǎn · noedelzaak (noodle shop). In Taiwan or Hong Kong you may see this written with traditional characters as 麵館 instead.',
      { hanzi: '面馆', pinyin: 'miànguǎn', nl: 'noedelzaak' },
    ],
    [
      'On a shopfront. What is this place?',
      ['hotpot', 'restaurant or hotel', 'local police station', 'restaurant'],
      0,
      'huǒguō · hotpot. 锅 (pot) uses the 钅 (metal) radical, common in words for cookware.',
      { hanzi: '火锅', pinyin: 'huǒguō', nl: 'hotpot' },
    ],
    [
      'On a shopfront. What is this place?',
      ['coffee', 'hotel (mid-range)', 'laundry', 'snacks, cheap eats'],
      0,
      'kāfēi · koffie (coffee). Both characters share the 口 (mouth) radical, a hint that this word is a sound-based borrowing from a foreign language rather than a word built from meaning.',
      { hanzi: '咖啡', pinyin: 'kāfēi', nl: 'koffie' },
    ],
    [
      'On a shopfront. What is this place?',
      ['tea', 'petrol station', 'pharmacy', 'hotel (mid-range)'],
      0,
      'chá · thee (tea). Look for it in 茶楼 (teahouse) and 奶茶 (bubble tea).',
      { hanzi: '茶', pinyin: 'chá', nl: 'thee' },
    ],
  ],
};
