#!/usr/bin/env python3
"""
Subset the CJK faces to exactly the characters the item bank uses.

Noto Sans SC ships as ~100 per-range files and no single one covers the bank, so
each needed character is subsetted from whichever file has it and the parts are
merged back into one file per face. One request per face instead of forty-seven,
and about 48 KB instead of the 1.1 MB the full simplified subset costs.

The build FAILS if a character in the bank is in none of the produced subsets. A
missing glyph is a tofu box, and a tofu box in a game about reading characters is
unrecoverable at a restaurant table with no signal.

Two characters are absent from every Noto Sans/Serif SC file and are drawn as SVG
in the breakdown surface instead — never replaced by a homoglyph, per DESIGN.md
§3.3.4:

    ⺼ U+2EBC CJK RADICAL MEAT      ⺮ U+2EAE CJK RADICAL BAMBOO

⺼ is the one that matters: it is the component in 肝 肠 肚 腰 脑, it is visually
identical to 月 U+6708 (moon), and substituting the moon is the exact error the
whole ruling exists to prevent.
"""
import glob, os, subprocess, sys, tempfile
from fontTools.merge import Merger
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'apps/pwa/src/fonts')
NM = os.path.join(ROOT, 'apps/pwa/node_modules')

FACES = [
    ('@fontsource/noto-sans-sc', 400, 'Kanbudong Han Sans', 'han-sans-400'),
    ('@fontsource/noto-sans-sc', 500, 'Kanbudong Han Sans', 'han-sans-500'),
    ('@fontsource/noto-sans-sc', 700, 'Kanbudong Han Sans', 'han-sans-700'),
    ('@fontsource/noto-serif-sc', 700, 'Kanbudong Han Serif', 'han-serif-700'),
]
DRAWN = {0x2EBC, 0x2EAE}
UI_CHROME = '看不懂价斤质付炒肉辣单店折营楼禁心请出铁票'


def bank_characters():
    chars = set()
    for path in glob.glob(os.path.join(ROOT, 'packages/engine/src/content/**/*.ts'), recursive=True):
        for ch in open(path, encoding='utf-8').read():
            cp = ord(ch)
            if (0x2E80 <= cp <= 0x2FFF or 0x3400 <= cp <= 0x9FFF or 0xF900 <= cp <= 0xFAFF):
                chars.add(ch)
    chars |= set(UI_CHROME)
    return {c for c in chars if ord(c) not in DRAWN}


def cmap_of(path):
    try:
        font = TTFont(path, lazy=True)
        cm = set()
        for t in font['cmap'].tables:
            cm |= set(t.cmap.keys())
        font.close()
        return cm
    except Exception:
        return set()


def build(pkg, weight, family, tag, need, tmp):
    files = sorted(glob.glob(os.path.join(NM, pkg, 'files', f'*-{weight}-normal.woff2')))
    if not files:
        sys.exit(f'FAIL: no {weight}-weight files in {pkg}. Did pnpm install run?')
    parts, unseen = [], set(need)
    for src in files:
        if not unseen:
            break
        hit = {c for c in unseen if ord(c) in cmap_of(src)}
        if not hit:
            continue
        part = os.path.join(tmp, f'{tag}-{len(parts):03d}.ttf')
        txt = os.path.join(tmp, 'chars.txt')
        open(txt, 'w', encoding='utf-8').write(''.join(sorted(hit)))
        subprocess.run(['pyftsubset', src, f'--text-file={txt}', f'--output-file={part}',
                        '--layout-features=', '--no-hinting', '--desubroutinize'], check=True)
        parts.append(part)
        unseen -= hit

    dst = os.path.join(OUT, f'{tag}.woff2')
    merged = Merger().merge(parts) if len(parts) > 1 else TTFont(parts[0])
    merged.flavor = 'woff2'
    merged.save(dst)

    present = cmap_of(dst)
    missing = sorted(c for c in need if ord(c) not in present)
    size = os.path.getsize(dst) / 1024
    print(f'  {tag:<15} {len(parts):>2} source ranges → {size:>5.1f} KB, '
          f'{len(need) - len(missing)}/{len(need)} characters')
    return missing


def main():
    os.makedirs(OUT, exist_ok=True)
    need = bank_characters()
    print(f'bank needs {len(need)} CJK characters ({len(DRAWN)} more are drawn, not typeset)')

    css = ['/* GENERATED by scripts/build-fonts.py — do not edit; run `pnpm fonts`. */',
           '/* Noto Sans SC / Noto Serif SC, SIL Open Font License 1.1 — see OFL.txt. */',
           '/* Subsets to the item bank, renamed per OFL clause 3. */', '']
    failures = {}
    with tempfile.TemporaryDirectory() as tmp:
        for pkg, weight, family, tag in FACES:
            missing = build(pkg, weight, family, tag, need, tmp)
            if missing:
                failures[tag] = missing
            css += ['@font-face {', f"  font-family: '{family}';", '  font-style: normal;',
                    f'  font-weight: {weight};', '  font-display: swap;',
                    f"  src: url('./{tag}.woff2') format('woff2');", '}', '']

    open(os.path.join(OUT, 'fonts.css'), 'w', encoding='utf-8').write('\n'.join(css))
    total = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT) if f.endswith('.woff2'))
    print(f'total: {total / 1024:.0f} KB across {len(FACES)} faces')

    if failures:
        print('\nFAIL: characters in the bank are missing from a produced subset:', file=sys.stderr)
        for tag, gone in failures.items():
            print(f'  {tag}: {"".join(gone)}', file=sys.stderr)
        print('  Add a face that covers them, or draw them. Never substitute a homoglyph.', file=sys.stderr)
        sys.exit(1)
    print('coverage verified: every bank character is present in every face')


if __name__ == '__main__':
    main()
